version: '3.7'
services:
    dbmysql:
        image: mysql
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=$ROOT_PASS
          - MYSQL_DATABASE=$DB
          - MYSQL_USER=$USER
          - MYSQL_PASSWORD=$PASS
        ports:
          - 3000:3306
        volumes:
          - ./db:/docker-entrypoint-initdb.d        
    node:
        #build: .
        image: node:lts-stretch-slim
        volumes:
          - ./:/usr/src/app
        command: npm run start:dev --prefix /usr/src/app
        restart: always
        ports:
          - 8080:8080
        environment:
          - MYSQL_ROOT_PASSWORD=$ROOT_PASS
          - MYSQL_DATABASE=$DB
          - MYSQL_HOST=$HOST
          - MYSQL_PORT=$PORT
          - MYSQL_USER=$USER
          - MYSQL_PASSWORD=$PASS
        env_file:
          - .env
        depends_on:
          - dbmysql