version: '3.7'
services:
    dbmysql:
        image: mysql
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=GraphDB
          - MYSQL_USER=user
          - MYSQL_PASSWORD=root
        ports:
          - 3000:3306
        volumes:
          - ./db:/docker-entrypoint-initdb.d        
    node:
        #build: .
        image: node:lts-stretch-slim
        volumes:
          - ./:/usr/src/app
        command: npm run start:dev --prefix /usr/src/app
        restart: always
        ports:
          - 8080:8080
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=GraphDB
          - MYSQL_HOST=dbmysql
          - MYSQL_PORT=3306
          - MYSQL_USER=user
          - MYSQL_PASSWORD=root
        env_file:
          - .env
        depends_on:
          - dbmysql